# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('facebook_id', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('quantidade_semana', models.IntegerField(default=1)),
                ('pago_ate', models.DateField(null=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Feirante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('organico', models.BooleanField()),
                ('cota_alface', models.IntegerField(default=0)),
                ('cota_tomate', models.BooleanField(default=0)),
                ('cota_cheiroverde', models.BooleanField(default=0)),
                ('cota_couve', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ('nome', 'organico'),
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('organico', models.BooleanField(default=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_alface', models.BooleanField(default=True)),
                ('item_tomate', models.BooleanField(default=True)),
                ('item_cheiroverde', models.BooleanField(default=True)),
                ('item_couve', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome', 'organico'),
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organico', models.BooleanField(default=False)),
                ('item', models.IntegerField(choices=[(1, 'Alface'), (2, 'Tomate'), (3, 'Cheiro Verde'), (4, 'Couve')], default='1')),
                ('data', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.Cliente')),
                ('feirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horta.Feirante')),
            ],
            options={
                'ordering': ('data', 'cliente'),
            },
        ),
    ]
