# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0002_auto_20170429_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Ok')], default='1'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='feirante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='horta.Feirante'),
        ),
    ]
