# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0003_auto_20170429_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='feirante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horta.Feirante'),
        ),
    ]
