# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0004_auto_20170429_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Terça'), (2, 'Quinta')], default='1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pago_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='feirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horta.Feirante'),
        ),
    ]
