# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0006_auto_20170429_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Ok')], default='1'),
        ),
    ]
