# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0007_pagamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
