# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horta', '0009_auto_20170429_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feirante',
            name='cota_cheiroverde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feirante',
            name='cota_couve',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feirante',
            name='cota_tomate',
            field=models.IntegerField(default=0),
        ),
    ]
