# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('category', models.IntegerField(choices=[(1, 'Dengue'), (1, 'Dengue hemorr\xe1gica')], default='1')),
                ('city', models.IntegerField(choices=[(1, 'Palmas'), (2, 'Porto Nacional'), (3, 'Para\xedso do Tocantins')], default='1')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
